[package]
name = "ltc2949"
description = "Client for the battery pack monitor chip LTC2949"
keywords = ["LTC2949", "BMS", "no_std", "battery", "ic"]
categories  = ["embedded", "hardware-support", "no-std"]
authors = ["Neomium GmbH <info@neomium.de>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/neomium/rt-LTC2949"
readme = "README.md"
documentation = "https://docs.rs/ltc2949"

[dependencies]
embedded-hal = "1.0.0"
heapless = "0.9.3"
modular-bitfield = "0.13.1"
ltc681x = {optional = true, version = "0.6.2"}

[dev-dependencies]
mockall = "0.11.0"

[features]
default = ["example"]
# Mocks and dependencies for doc examples
example = ["ltc681x"]
# Fail on warnings
strict = []